<option data-cat="22">Все</option>
<option data-cat="26">Абстрактные изображения</option>
<option data-cat="24">Винтаж</option>
<option data-cat="6">Еда и напитки</option>
<option data-cat="1">Животные/Дикая природа</option>
<option data-cat="2">Здания/Достопримечательности</option>
<option data-cat="11">Искусство</option>
<option data-cat="25">Парки/Природа</option>
<option data-cat="9">Предметы</option>
<option data-cat="12">Природа</option>
<option data-cat="0">Транспорт</option>
<option data-cat="22">Разное</option>
<option data-cat="18">Спорт/Отдых</option>
<!-- <option data-cat="Any">Все</option>
<option data-cat="Abstract">Абстрактные изображения</option>
<option data-cat="Vintage">Винтаж</option>
<option data-cat="Food and Drink">Еда и напитки</option>
<option data-cat="Animals/Wildlife">Животные/Дикая природа</option>
<option data-cat="Buildings/Landmarks">Здания/Достопримечательности</option>
<option data-cat="The Arts">Искусство</option>
<option data-cat="Parks/Outdoor">Парки/Природа</option>
<option data-cat="Objects">Предметы</option>
<option data-cat="Nature">Природа</option>
<option data-cat="Transportation">Транспорт</option>
<option data-cat="Miscellaneous">Разное</option>
<option data-cat="Sports/Recreation">Спорт/Отдых</option> -->